/* =====================================================================
   CHAPTER 5 — VERİ BİLİMCİ (3,5 yıl sonra), VAKA 033–040
   Zincir: model karşılaştırma → segmentasyon → model trade-off →
   kalibrasyon/eşik → XAI → forecasting → GenAI değerlendirme → canlı aday
   Rehberlik: yalnızca vaka sonu değerlendirmesi.
   ===================================================================== */
CH_START[5] = 33;
PROMOTIONS[5] = { title: "Kıdemli Veri Bilimci", req: { modeling: 4, evaluation: 4, xai: 2, calibration: 2, genai: 2, forecasting: 3, "evaluation@2": 3 } };
CH_PROMO_CASE[5] = "case040";

const CH5_CASES = [
{ id:"case033",num:"033",chapter:5,title:"Kim Ayrılacak?",difficulty:4,xp:250,after:"case032",short:"Aynı veri, üç model. En yüksek skoru değil en güvenilir adayı seç.",tags:["Model karşılaştırma","CV","İş maliyeti"],nodes:["modeling","evaluation"],rewards:{statistics:8,businessThinking:8},
 concept:{name:"Model karşılaştırma",en:"model comparison",text:"Modelleri aynı split, aynı metrik ve aynı iş koşulunda karşılaştırmak; küçük skor farkını otomatik zafer saymamak.",points:[]},mentor:"Kazanan model, leaderboard'un ilk satırı değil; karar bağlamında en güvenilir adaydır.",portfolio:{title:"Churn model seçimi",text:"Üç modeli aynı zamansal doğrulama ve hata maliyeti altında karşılaştırıp kararlı adayı seçtim."},review:{happened:"Boosting tek bir ayda öndeydi ama dönemler arasında daha oynaktı.",discovered:"Ortalama skor kadar varyasyon, maliyet ve açıklanabilirlik de model seçimidir.",habit:"Aynı split + aynı metrik + dönem bazlı kararlılık + iş maliyeti.",watch:"Test setini model seçmek için tekrar tekrar kullanma."},steps:[
 {type:"dialog",who:"maya",cta:"Adaylara bak",lines:["3,5 yıl oldu. Artık senden model kurmanı değil, model seçmeni bekliyorum.","Üç aday var. Yönetim öğleden sonra bir isim istiyor."]},
 {type:"choice",label:"Karşılaştır",prompt:"Hangisini pilot adayı yaparsın?",goal:"Tek skora değil kararlılık ve maliyete bakmak.",visual:()=>dataTable(["Model","AUC (3 ay)","Aylık maliyet","Not"],[["Lojistik",".82 / .83 / .82","164K ₺","kararlı"],["Random Forest",".85 / .78 / .84","171K ₺","oynak"],["Boosting",".86 / .85 / .85","151K ₺","kararlı"]]),options:[{label:"Random Forest; bir ay .85 gördü",fb:"Tek aya göre seçim yapıyorsun."},{label:"Boosting; aynı doğrulamada daha kararlı ve iş maliyeti daha düşük",correct:true,fb:"Doğru. Farkı pilotta doğrulayacağız."}]},
 {type:"choice",label:"Transfer",transfer:true,prompt:"Yeni model AUC'yi .85'ten .852'ye çıkarıyor ama gecikme 5 kat. Ne yaparsın?",goal:"Teknik kazanımı sistem maliyetiyle tartmak.",options:[{label:"Skor yüksekse değiştiririm",fb:"Kazanım marjinal, sistem bedeli büyük."},{label:"İş etkisi anlamlı değilse mevcut modeli korurum",correct:true,fb:"Model seçimi optimizasyon değil karar problemidir."}]}
]},
{ id:"case034",num:"034",chapter:5,title:"Müşteri DNA'sı",difficulty:4,xp:250,after:"case033",short:"Pazarlama '5 segment' istiyor. Küme sayısını slayt değil veri belirlesin.",tags:["Clustering","Ölçekleme","Segment yorumlama"],nodes:["modeling","business"],rewards:{dataExploration:8,businessThinking:8},
 concept:{name:"Kümeleme",en:"clustering",text:"Etiketsiz veride benzer gözlemleri gruplamak; ölçek, değişken seçimi ve işte kullanılabilirlik sonucu belirler.",points:[]},mentor:"K-means sana müşteri personası vermez. Sadece benzer noktaları gruplar; anlamı sen verirsin.",portfolio:{title:"Müşteri segmentasyonu",text:"Ölçeklenmiş davranış değişkenleriyle segmentleri kurup pazarlama aksiyonuna çevirdim."},review:{happened:"Gelir değişkeni ölçeklenmeyince kümeleri tek başına domine etti.",discovered:"Clustering'de preprocessing modelin parçasıdır.",habit:"Ölçekle → birkaç k dene → kararlılığı ve iş yorumunu kontrol et.",watch:"Kümelere sonradan stereotipik anlamlar yükleme."},steps:[
 {type:"choice",label:"Hazırla",prompt:"Harcamalar 0–100.000 ₺, ziyaret 0–30. K-means öncesi ne yaparsın?",goal:"Ölçek farkını kontrol etmek.",options:[{label:"Olduğu gibi kullanırım",fb:"Harcama uzaklığı domine eder."},{label:"Davranış değişkenlerini ölçekler, kimlik/PII alanlarını dışarıda bırakırım",correct:true,fb:"Doğru başlangıç."}]},
 {type:"choice",label:"Küme sayısı",prompt:"k=4 silhouette .41, k=5 .42, k=6 .40. Pazarlama 5 istiyor. Kararın?",goal:"Skor ve iş yorumunu birlikte kullanmak.",options:[{label:"5 kesin bilimsel optimum",fb:"Fark çok küçük."},{label:"4 ve 5'i kararlılık/yorumlanabilirlik açısından karşılaştırır, aksiyona dönüşeni seçerim",correct:true,fb:"Clustering'de tek metrik kutsal değil."}]},
 {type:"choice",label:"Transfer",transfer:true,prompt:"Kümelerden biri yalnızca yaşa göre ayrışıyor. Ne kontrol edersin?",goal:"Segmentlerin sorumlu kullanımını sorgulamak.",options:[{label:"Yaşı isim olarak kullanıp kampanyayı başlatırım",fb:"Hassasiyet ve stereotip riski."},{label:"Değişken gerekliliği, adillik ve aksiyonun meşru amacını yeniden incelerim",correct:true,fb:"Segment üretmek kullanım izni değildir."}]}
]},
{ id:"case035",num:"035",chapter:5,title:"Ağaç mı Doğrusal mı?",difficulty:4,xp:250,after:"case034",short:"Biraz daha iyi skor mu, daha basit operasyon mu?",tags:["Trade-off","Complexity","Latency"],nodes:["modeling","evaluation"],rewards:{businessThinking:10,statistics:6},
 concept:{name:"Model trade-off",en:"model trade-off",text:"Performans, gecikme, bakım, açıklanabilirlik ve veri ihtiyacını birlikte değerlendirerek model seçmek.",points:[]},mentor:"Üretimde modelin bir yaşam maliyeti vardır.",portfolio:{title:"Model trade-off kararı",text:"Skor farkını latency, bakım ve iş etkisiyle birlikte değerlendirerek model seçtim."},review:{happened:"Karmaşık model yalnızca küçük skor kazanımı sağlıyordu.",discovered:"En iyi offline model her zaman en iyi ürün değildir.",habit:"Skor farkını mutlak değil, iş etkisi ve sistem maliyetiyle oku.",watch:"Basitlik bahanesiyle anlamlı kazanımı da reddetme."},steps:[
 {type:"choice",label:"Karar",prompt:"Model A: AUC .872, 25 ms, aylık bakım 2 saat. Model B: .881, 480 ms, aylık bakım 20 saat. Gerçek zamanlı teklif sistemi. İlk tercih?",goal:"Performans ve operasyonu birlikte tartmak.",options:[{label:"B; AUC daha yüksek",fb:"9 bps kazanımın sistem bedelini yok saydın."},{label:"A'yı varsayılan aday yapar, B'nin ek iş değerini pilotta kanıtlamasını isterim",correct:true,fb:"Doğru trade-off."}]},
 {type:"choice",label:"Transfer",transfer:true,prompt:"B modeli yıllık 4M ₺ ek değer üretiyorsa?",goal:"Trade-off kararını yeni bilgiyle güncellemek.",options:[{label:"Yine A; basit her zaman iyidir",fb:"Yeni iş etkisini yok sayıyorsun."},{label:"B'nin operasyon maliyetini çıkarıp net değeri pozitifse mimariyi B için değerlendiririm",correct:true,fb:"Karar veri geldikçe değişebilir."}]}
]},
{ id:"case036",num:"036",chapter:5,title:"Eşiği Kim Belirler?",difficulty:4,xp:260,after:"case035",short:"İyi sıralama yetmez. Olasılık doğru mu ve hangi eşik para kazandırıyor?",tags:["Calibration","Threshold","Cost"],nodes:["evaluation","calibration"],rewards:{statistics:10,businessThinking:8},
 concept:{name:"Kalibrasyon ve eşik",en:"calibration & threshold",text:"Ayırt etme gücünü olasılık doğruluğundan ayırmak ve karar eşiğini hata maliyetine göre seçmek.",points:[]},mentor:"0,8 bir skor mu, gerçekten %80 olasılık mı? Bu ayrım bütçe kararını değiştirir.",portfolio:{title:"Kalibre karar eşiği",text:"Olasılık kalibrasyonunu kontrol edip iş maliyetini minimize eden eşiği seçtim."},review:{happened:"Model sıralamada iyiydi fakat %80 dediği grubun yalnızca %53'ü churn ediyordu.",discovered:"AUC kalibrasyonu garanti etmez.",habit:"Önce calibration curve; sonra maliyet/kapasite ile threshold.",watch:"Dağılım değişince kalibrasyon da bozulabilir."},steps:[
 {type:"choice",label:"Teşhis",prompt:"0,8–0,9 skor grubunda gerçek churn %53. Sorun ne?",goal:"Discrimination ile calibration'ı ayırmak.",options:[{label:"AUC kesin düşüktür",fb:"Sıralama hâlâ iyi olabilir."},{label:"Olasılıklar aşırı güvenli; model kalibre değil",correct:true,fb:"Doğru."}]},
 {type:"builder",label:"Eşik",prompt:"Kalibrasyon sonrası teklif eşiğini seç.",goal:"İş maliyetini minimize etmek.",fields:[{key:"thr",label:"Eşik",options:[["30","0,30 — maliyet 182K"],["40","0,40 — maliyet 147K"],["50","0,50 — maliyet 156K"],["60","0,60 — maliyet 201K"]]}],run:"Kararı uygula",visual:d=>noteCard("Aylık karar maliyeti",d.thr?`Seçilen eşik: 0,${d.thr}`:"Bir eşik seç"),check:d=>d.thr==="40"?{ok:true,title:"En düşük beklenen maliyet",fb:"0,40 varsayılan 0,50'den daha iyi iş kararı."}:{ok:false,fb:"Model metriği değil toplam hata maliyetini minimize et."}},
 {type:"choice",label:"Transfer",transfer:true,prompt:"Kredi risk modeli sıralamada iyi ama PD'leri sistematik düşük tahmin ediyor. Ne etkilenir?",goal:"Kalibrasyonun iş etkisini taşımak.",options:[{label:"Sadece grafik görünümü",fb:"Olasılık fiyatlama/sermaye kararını etkiler."},{label:"Risk fiyatlama ve eşik kararları; yeniden kalibrasyon gerekir",correct:true,fb:"Doğru."}]}
]},
{ id:"case037",num:"037",chapter:5,title:"Bu Tahmini Açıkla",difficulty:4,xp:260,after:"case036",short:"CEO genel nedeni, müşteri temsilcisi tekil nedeni soruyor.",tags:["XAI","Global","Local"],nodes:["xai","evaluation"],rewards:{communication:10,businessThinking:6},
 concept:{name:"Açıklanabilirlik",en:"explainability",text:"Global model davranışı ile tek bir tahminin yerel açıklamasını ayırmak ve açıklamayı karar verene göre sunmak.",points:[]},mentor:"Açıklama, modelin bahanesi değildir. Doğru soruya doğru seviyede kanıttır.",portfolio:{title:"XAI değerlendirmesi",text:"Global ve local açıklamayı ayırıp açıklamanın nedensellik olmadığını yönetime aktardım."},review:{happened:"Global feature importance tek müşterinin neden yüksek risk aldığını açıklamıyordu.",discovered:"Global ve local açıklama farklı sorulara cevap verir.",habit:"Kime açıklıyorum? Hangi karar için? Global mi local mi?",watch:"SHAP değeri nedensel etki değildir."},steps:[
 {type:"choice",label:"CEO",prompt:"CEO: 'Model genel olarak neye bakıyor?'",goal:"Global açıklamayı seçmek.",options:[{label:"Tek müşterinin SHAP waterfall'ı",fb:"Bu local açıklama."},{label:"Global önem/etki özeti ve segment bazlı davranış",correct:true,fb:"Doğru seviye."}]},
 {type:"choice",label:"Müşteri",prompt:"Temsilci: 'Ayşe neden yüksek risk aldı?'",goal:"Local açıklamayı seçmek.",options:[{label:"Global feature importance",fb:"Ayşe özelinde cevap değil."},{label:"Ayşe'nin skorunu yukarı/aşağı iten özelliklerin local açıklaması",correct:true,fb:"Doğru."}]},
 {type:"choice",label:"Transfer",transfer:true,prompt:"SHAP'ta 'destek çağrısı sayısı' skoru artırıyor. 'Destek çağrısı churn'e neden olur' diyebilir misin?",goal:"Açıklama ile nedenselliği ayırmak.",options:[{label:"Evet",fb:"Model ilişkisini nedensellik sandın."},{label:"Hayır; model ilişkisini açıklar, nedensel etkiyi kanıtlamaz",correct:true,fb:"Kritik ayrım."}]}
]},
{ id:"case038",num:"038",chapter:5,title:"Yarının Satışları",difficulty:4,xp:270,after:"case037",short:"Forecast yarışında modelden önce horizon ve backtest tasarımını savun.",tags:["Forecasting","Backtest","Uncertainty"],nodes:["forecasting","evaluation"],rewards:{statistics:10,dataExploration:8},
 concept:{name:"Forecast backtesting",en:"forecast backtesting",text:"Tahmin ufkunu iş kararına göre tanımlamak, zamansal backtest yapmak ve naif baseline ile karşılaştırmak.",points:[]},mentor:"Forecast'ın testi geleceği taklit etmelidir.",portfolio:{title:"Satış forecast tasarımı",text:"3 aylık ufuk için rolling-origin backtest, seasonal-naive baseline ve belirsizlik bandı kurdum."},review:{happened:"Rastgele split geçmiş ve geleceği karıştırıyordu.",discovered:"Forecast değerlendirmesi üretimdeki tahmin anını tekrar etmelidir.",habit:"Horizon → naive baseline → rolling backtest → hata + interval.",watch:"Tek toplam WMAPE segment hatalarını saklayabilir."},steps:[
 {type:"choice",label:"Ufuk",prompt:"Tedarik ekibi 3 ay önceden sipariş veriyor. Hangi forecast tasarımı?",goal:"Horizon'u iş kararına bağlamak.",options:[{label:"1 gün sonrası tahmin",fb:"İş kararına yetişmiyor."},{label:"1–3 ay ileri ufuk; her origin'de gerçek üretim akışını taklit et",correct:true,fb:"Doğru."}]},
 {type:"choice",label:"Backtest",prompt:"Hangisi dürüst?",goal:"Zamansal değerlendirmeyi seçmek.",options:[{label:"Tüm ayları rastgele train/test",fb:"Zaman sırası bozulur."},{label:"Rolling-origin: geçmişle eğit, sonraki 3 ayı test et, origin'i ilerlet",correct:true,fb:"Üretimi taklit eder."}]},
 {type:"choice",label:"Transfer",transfer:true,prompt:"Yeni model WMAPE %12, seasonal-naive %11. Ne dersin?",goal:"Baseline refleksini forecasting'e taşımak.",options:[{label:"Yeni model daha modern, seçerim",fb:"Baseline'ı geçemiyor."},{label:"Naive'ı korur, modelin nerede değer ürettiğini hata analiziyle araştırırım",correct:true,fb:"Doğru."}]}
]},
{ id:"case039",num:"039",chapter:5,title:"LLM'i Nasıl Ölçeriz?",difficulty:4,xp:280,after:"case038",short:"RAG chatbot demosu etkileyici. Ama demo değerlendirme değildir.",tags:["GenAI Eval","RAG","Hallucination"],nodes:["genai","evaluation","privacy"],rewards:{businessThinking:8,communication:8},
 concept:{name:"LLM değerlendirme",en:"LLM evaluation",text:"Temsil edici eval setiyle doğruluk, groundedness, retrieval başarısı, güvenlik, maliyet ve gecikmeyi ayrı ölçmek.",points:[]},mentor:"LLM'de 'güzel cevap verdi' metrik değildir.",portfolio:{title:"RAG eval planı",text:"RAG sistemini retrieval ve generation hatalarını ayıran, groundedness ve güvenlik içeren eval setiyle değerlendirdim."},review:{happened:"Demo soruları sistemin bildiği örneklerden seçilmişti.",discovered:"RAG hatası retrieval'dan da generation'dan da gelebilir.",habit:"Eval set → retrieval → groundedness → task success → safety → cost/latency.",watch:"LLM-as-judge tek başına ground truth değildir."},steps:[
 {type:"choice",label:"Eval set",prompt:"İlk gerçek değerlendirme ne olmalı?",goal:"Temsil edici eval seti kurmak.",options:[{label:"Takımın sevdiği 10 demo sorusu",fb:"Cherry-pick riski."},{label:"Gerçek kullanım dağılımından, zor/başarısız/güvenlik örnekleri içeren etiketli eval seti",correct:true,fb:"Doğru."}]},
 {type:"choice",label:"Hata kökü",prompt:"Doğru politika dokümanı retrieval top-5'e hiç gelmedi; cevap uyduruldu. Ana hata nerede?",goal:"Retrieval ve generation hatasını ayırmak.",options:[{label:"Sadece prompt",fb:"Model doğru kaynağı hiç görmedi."},{label:"Önce retrieval başarısız; generation da kaynaksız cevap vererek ikinci hata yaptı",correct:true,fb:"İki katman ayrı ölçülmeli."}]},
 {type:"choice",label:"Transfer",transfer:true,prompt:"Prompt ile düzelmeyen güncel şirket bilgisi soruları var. İlk mimari aday?",goal:"Prompt/RAG/fine-tune ayrımını kullanmak.",options:[{label:"Her gün fine-tune",fb:"Güncel bilgi için pahalı ve uygunsuz."},{label:"RAG; güncel kaynağı getir, cevabı kaynakla sınırla",correct:true,fb:"Doğru başlangıç."}]}
]},
{ id:"case040",num:"040",chapter:5,title:"Canlı Aday",difficulty:5,xp:340,after:"case039",promotion:true,short:"Model, forecast ve GenAI sistemlerinden hangisi canlıya hazır? Kararı savun.",tags:["Promotion","Production decision","Risk"],nodes:["modeling","evaluation","xai","calibration","genai","forecasting"],rewards:{businessThinking:12,communication:12,statistics:8},
 concept:{name:"Canlıya alma kararı",en:"production readiness",text:"Offline performansın ötesinde kalibrasyon, açıklanabilirlik, veri sözleşmesi, izleme, rollback ve iş etkisini birlikte değerlendirmek.",points:[]},mentor:"Bugün model seçmiyorsun. Hangi sistemin kontrollü biçimde gerçek kullanıcıya dokunabileceğine karar veriyorsun.",portfolio:{title:"Production readiness review",text:"Üç AI/ML adayını performans, risk, izleme ve geri alma planıyla değerlendirip kontrollü canlıya alma kararı verdim."},review:{happened:"En yüksek skorlu adayın monitoring ve rollback planı yoktu.",discovered:"Production readiness offline skorun devamı değil, ayrı bir güvence problemidir.",habit:"Data contract → eval → calibration/XAI → monitoring → pilot → rollback → business KPI.",watch:"Chapter 6'da bu sistemler gerçekten bozulacak."},steps:[
 {type:"dialog",who:"maya",cta:"Review'u aç",lines:["Üç ekip üç sistem getirdi. Birini bu ay canlıya alabiliriz.","Bu kez doğru cevap bir algoritma adı değil; riskleriyle birlikte bir karar."]},
 {type:"choice",label:"Aday",prompt:"Hangisi kontrollü canlıya almaya en hazır?",goal:"Production readiness'i sentezlemek.",visual:()=>dataTable(["Aday","Offline","Güvence","Eksik"],[["Churn Boosting","AUC .89","kalibre + XAI + pilot","drift dashboard taslak"],["Forecast","WMAPE %10","3 backtest + baseline","interval coverage eksik"],["RAG Bot","task %86","eval set + kaynak gösterme","PII red-team eksik"]]),options:[{label:"RAG; kullanıcıya en görünür",fb:"PII red-team eksik."},{label:"Forecast; WMAPE en kolay anlatılır",fb:"Belirsizlik kapsamı eksik."},{label:"Churn; sınırlı pilot + monitoring şartıyla",correct:true,fb:"En az açık risk ve geri dönüşü kolay pilot."}]},
 {type:"choice",label:"Guardrail",prompt:"Pilot başlamadan son kontrol?",goal:"Canlı sistem güvence zincirini kurmak.",options:[{label:"Sadece AUC dashboard'u",fb:"İş ve sistem sağlığını kaçırır."},{label:"Veri dağılımı, skor/kalibrasyon, teklif maliyeti, churn etkisi ve rollback eşiği",correct:true,fb:"Üretim düşüncesi başladı."}]},
 {type:"reply",label:"Karar notu",who:"maya",prompt:"Maya: “Yönetim kuruluna tek cümle?”",options:[{label:"En iyi modelimizi canlıya alıyoruz.",reply:"Maya: “Hangi anlamda en iyi? Bu cümle kuruldan dönüyor.”"},{label:"Kalibre edilmiş churn modelini sınırlı pilotta, iş etkisi ve drift guardrail'leriyle devreye alıp önceden tanımlı rollback eşiğinde geri çekeceğiz.",reply:"Maya: “Artık yalnız model geliştirmiyorsun; sistem sahipleniyorsun.”",flag:{prod_model:"calibrated_monitored"}}]},
 {type:"choice",label:"Transfer",transfer:true,prompt:"Canlıda offline metrik aynı kalırken iş etkisi düşerse ilk refleks?",goal:"Chapter 6'ya köprü kurmak.",options:[{label:"Modeli hemen daha karmaşık yaparım",fb:"Önce sistemde ne değiştiğini bul."},{label:"Veri/konsept kayması, aksiyon uygulanması ve iş metriği zincirini incelerim",correct:true,fb:"Kıdemli Veri Bilimci seviyesinin ilk sorusu."}]}
]}
];
CH5_CASES.forEach(c=>{c.kind="case";c.concept.points=[c.review.habit];CASES.push(c);CASE_BY_ID[c.id]=c;});

/* Kanıt kaynakları */
(()=>{const src={
 "mo.overfit":["case033","case035"],"mo.baseline":["case033","case038"],"ev.error":["case033","case035","case040"],"ev.threshold":["case036","case040"],"ev.pr":["case036"],
 "cal.prob":["case036","case040"],"cal.disc":["case036"],"xai.global":["case037","case040"],"xai.local":["case037"],
 "fc.baseline":["case038"],"fc.backtest":["case038","case040"],"gen.eval":["case039","case040"],"gen.rag":["case039"],"gen.choice":["case039"]};
 Object.entries(src).forEach(([cid,s])=>{const n=SKILL_TREE.find(n=>n.concepts.some(c=>c.id===cid));if(!n)return;const c=n.concepts.find(c=>c.id===cid);s.forEach(x=>{if(!c.src.includes(x))c.src.push(x)});CONCEPT_BY_ID[cid]={...c,node:n.id};});})();

/* Bölüm 5 yan görevleri — kısa, ofis içi ve gerçekçilik odaklı */
const CH5_QUESTS=[
 {id:"sq_ch5_modelcard",kind:"quest",modal:true,hot:"alex",who:"alex",after:"case033",title:"Model Kartında Eksik Satır",xp:45,rewards:{communication:5},lesson:"Model kartında performans kadar veri dönemi, intended use, limitler ve owner da yazmalıdır.",steps:[{type:"dialog",who:"alex",cta:"Bakayım",lines:["Model kartını göndereceğim ama bir şey eksik hissediyorum.","AUC var, algoritma var. Başka ne şart?"]},{type:"choice",prompt:"En kritik ekleme?",goal:"Model dokümantasyonunu karar bağlamına bağlamak.",options:[{label:"GPU modeli",fb:"Operasyon detayı olabilir ama karar bağlamı değil."},{label:"Intended use, veri dönemi, limitler ve model owner",correct:true,fb:"Alex: “Tamam. Modeli değil sorumluluğu da dokümante ediyoruz.”"}]}]},
 {id:"sq_ch5_coffee",kind:"quest",modal:true,hot:"coffee",who:"maya",after:"case036",title:"Kahve Makinesi %80 Emin",xp:35,rewards:{statistics:4},lesson:"%80 güven ifadesi ancak benzer %80 tahminlerin yaklaşık %80'i gerçekleşiyorsa olasılık anlamı taşır.",steps:[{type:"dialog",who:"maya",cta:"Sor",lines:["Kahve makinesi ekranda 'latte hazır olasılığı %80' yazıyor.","On denemenin beşinde hazır. Veri Bilimci refleksin?"]},{type:"choice",prompt:"Ne dersin?",goal:"Kalibrasyonu gündelik analojiyle pekiştirmek.",options:[{label:"%80 yüksek, sorun yok",fb:"Gerçekleşme %50."},{label:"Sıralama iyi olsa bile %80 olasılık kalibre görünmüyor",correct:true,fb:"Maya gülüyor: “Artık kahveye bile calibration curve çiziyorsun.”"}]}]},
 {id:"sq_ch5_buse_xai",kind:"quest",modal:true,hot:"lounge",who:"buse",after:"case037",title:"Buse SHAP'i Fazla Sevdi",xp:45,rewards:{communication:5},lesson:"Açıklanabilirlik yöntemi modelin kullandığı ilişkiyi açıklar; nedensellik kanıtlamaz.",steps:[{type:"dialog",who:"buse",cta:"Konuş",lines:["Buse: 'SHAP'a göre destek çağrısı churn'e neden oluyor. Destek ekibini azaltalım mı?'","Bir cümleyle durdurman gerekiyor."]},{type:"choice",prompt:"Cevabın?",goal:"XAI ile nedenselliği ayırmak.",options:[{label:"Evet, SHAP kanıtladı",fb:"Model ilişkisi nedensellik değildir."},{label:"SHAP tahmine katkıyı açıklar; neden-sonuç için ayrı tasarım gerekir",correct:true,fb:"Buse not alıyor: “Açıklama ≠ neden.”"}]}]},
 {id:"sq_ch5_rag",kind:"quest",modal:true,hot:"phone",who:"zeynep",after:"case039",title:"Chatbot Çok Emin",xp:50,rewards:{businessThinking:5},lesson:"Kaynağı olmayan kesin cevap, akıcı olsa da güvenilir değildir; abstention ve kaynak gösterme ürün davranışıdır.",steps:[{type:"dialog",who:"zeynep",cta:"Mesaja bak",lines:["Chatbot izin politikasını çok net anlattı ama link verdiği doküman yok.","Demo yarın. Bunu 'ufak hata' diye geçelim mi?"]},{type:"choice",prompt:"Ne yaparsın?",goal:"Hallucination için ürün guardrail'i seçmek.",options:[{label:"Metni daha kibar yaparız",fb:"Sorun ton değil doğruluk."},{label:"Kaynak yoksa cevap vermeme/uyarı davranışı ekler, groundedness eval'ine dahil ederim",correct:true,fb:"Zeynep: “Demo biraz daha az sihirli, çok daha güvenilir.”"}]}]}
];
CH5_QUESTS.forEach(q=>{QUESTS.push(q);QUEST_BY_ID[q.id]=q;});

/* Sabah mikro-sahneleri — bölüm boyunca ofisin yaşadığı hissi */
Object.assign(MORNINGS,{
 33:{scene:"timeskip",time:"08:32",title:"3,5 yıl sonra",text:"Yeni kartın: Veri Bilimci. Masanda iki monitör, üç model raporu ve soğumuş bir kahve.",steps:[{type:"dialog",who:"maya",cta:"Güne başla",lines:["Artık sana 'hangi modeli kurayım?' diye sormayacağım.","Soru şu: Hangisini neden seçiyorsun ve canlıda neye dönüşecek?"]}]},
 34:{scene:"standup",time:"09:07",title:"Pazarlama stand-up'ı",text:"Whiteboard'da büyük harflerle: '5 PERSONA LAZIM'.",steps:[{type:"dialog",who:"zeynep",cta:"Devam",lines:["Sunum cuma. Beş segment güzel görünür mü?","Senin yüz ifadenden bunun bilimsel bir kriter olmadığını anladım."]}]},
 35:{scene:"laptop",time:"08:49",title:"Latency alarmı",text:"Slack: 'Yeni model checkout'u 480 ms yavaşlatıyor.'",steps:[{type:"dialog",who:"alex",cta:"Bak",lines:["Offline yarışmayı kazandı.","Ama ürün ekibi onu hiç sevmiyor."]}]},
 36:{scene:"coffee",time:"08:44",title:"%80 ne demek?",text:"Maya kahve makinesinin yüzdesine bakıp sana bakıyor.",steps:[{type:"dialog",who:"maya",cta:"Gülümse",lines:["Bugün olasılıkların gerçekten olasılık olup olmadığını konuşacağız."]}]},
 37:{scene:"standup",time:"09:12",title:"Açıklama günü",text:"CEO ve müşteri temsilcisi aynı model için iki farklı soru gönderdi.",steps:[{type:"dialog",who:"buse",cta:"Başla",lines:["SHAP öğrendim. Artık her şeyi açıklayabiliyorum!","Maya uzaktan başını iki yana sallıyor."]}]},
 38:{scene:"rain",time:"08:37",title:"Yağmurlu forecast sabahı",text:"Tedarik toplantısı 10:00'da. Üç ay sonrasını bugün bilmek istiyorlar.",steps:[{type:"dialog",who:"maya",cta:"Takvimi aç",lines:["Forecast'ın doğruluğu kadar ne zaman üretildiği de önemli."]}]},
 39:{scene:"laptop",time:"08:53",title:"Chatbot demosu",text:"VirelioBot cevapları çok akıcı. Bir tanesi olmayan bir politika dokümanına link veriyor.",steps:[{type:"dialog",who:"zeynep",cta:"Eval'i aç",lines:["Demo çok güzel. Gerçek kullanıcılar da bu kadar nazik soru sorar mı?","Bugün sihri değil sistemi ölçeceğiz."]}]},
 40:{scene:"promo",time:"08:28",title:"Production Review",text:"Toplantı odasında üç ekip, üç aday sistem ve tek canlıya alma penceresi var.",steps:[{type:"dialog",who:"maya",cta:"İçeri gir",lines:["Bu bölümde modelleri geliştirdin.","Bugün hangisinin gerçek dünyaya dokunmaya hazır olduğuna karar vereceksin."]}]}
});
Object.entries(MORNINGS).forEach(([d,m])=>{if(+d>=33&&+d<=40)MORNING_DEFS[`morning${d}`]={id:`morning${d}`,kind:"morning",day:+d,...m};});
Object.assign(AFTER_CASE,{case033:"Alex koridorda seni bekliyor; model kartında bir satır eksik.",case034:"Pazarlama segment isimlerini tartışıyor. Yarın model trade-off'u.",case035:"Latency alarmı kapandı. Yarın olasılıkların anlamını test edeceksin.",case036:"Kahve makinesindeki %80 bile artık şüpheli. Yarın XAI.",case037:"Buse SHAP notlarını topluyor. Yarın forecast toplantısı.",case038:"Tedarik rolling backtest'i kabul etti. Yarın chatbot demosu.",case039:"RAG eval raporu hazır. Yarın Production Review.",case040:"Toplantı bitmedi. Maya senden sonra kalmanı istedi."});
ACHIEVEMENTS.promoted5={t:"Kıdemli Veri Bilimci",d:"Modelden canlı sisteme geçiş kararını riskleriyle birlikte savundun."};
