/* DATA TYCOON — Chapter 7 */
CH_START[7] = 49;
PROMOTIONS[7] = { title: "Veri Direktörü", req: {leadership:3,governance:2,"leadership@2":1} };
CH_PROMO_CASE[7] = "case054";
const CH7_CASES = [
{"id":"case049","num":"049","chapter":7,"title":"Buse’nin Model İncelemesi","difficulty":5,"xp":280,"after":"case048","short":"Artık kendi modelinden çok ekibin karar kalitesinden sorumlusun.","tags":["leadership","governance"],"nodes":["leadership","governance"],"rewards":{"businessThinking":8,"statistics":6},"concept":{"name":"Teknik mentorluk","en":"Teknik mentorluk","text":"Lider review hatayı bulur ama öğrenmeyi de tasarlar.","points":[]},"mentor":"Soruyu sor, zaman çizgisini görünür yap, kişiyi değil kararı eleştir.","portfolio":{"title":"Buse’nin Model İncelemesi","text":"Artık kendi modelinden çok ekibin karar kalitesinden sorumlusun."},"review":{"happened":"Buse leakage içeren feature kullanmıştı.","discovered":"Lider review hatayı bulur ama öğrenmeyi de tasarlar.","habit":"Soruyu sor, zaman çizgisini görünür yap, kişiyi değil kararı eleştir.","watch":"Nazik olmak belirsiz olmak değildir."},"steps":[{"type":"dialog","who":"buse","cta":"Devam","lines":["İlk churn modelimi bitirdim. AUC .97!","Yarın yönetime sunacağım."]},{"type":"choice","label":"Review","prompt":"cancel_request_date tahmin sonrasında oluşuyor. Nasıl geri bildirim verirsin?","goal":"Mentorluk kalitesi.","options":[{"label":"“Yanlış, ben düzeltirim”","fb":"Model düzelir, kişi gelişmez."},{"label":"“Bu bilgi tahmin anında var mı?” diye birlikte zaman çizgisi kurarım","correct":true,"fb":"Hatayı Buse buluyor; öğrenme kalıcı."}]},{"type":"choice","label":"Transfer","prompt":"Aynı hata ikinci kez oldu.","goal":"Koçluk ve standartlaştırma.","options":[{"label":"Sadece daha sert uyarırım","fb":"Sistem aynı kalır."},{"label":"Review checklist ve point-in-time testini takım standardına eklerim","correct":true,"fb":"Bireysel hatayı sistem öğrenmesine çevirdin."}],"transfer":true}]},
{"id":"case050","num":"050","chapter":7,"title":"Üç Ekip, Tek Metrik","difficulty":5,"xp":280,"after":"case049","short":"Growth, Finance ve Product “aktif müşteri”yi farklı tanımlıyor.","tags":["governance","kpi"],"nodes":["governance","kpi"],"rewards":{"businessThinking":8,"statistics":6},"concept":{"name":"Metrik yönetişimi","en":"Metrik yönetişimi","text":"Metrik yönetişimi tanım, owner, kaynak, zaman penceresi ve değişiklik süreci gerektirir.","points":[]},"mentor":"Metric contract oluştur ve tek owner ata.","portfolio":{"title":"Üç Ekip, Tek Metrik","text":"Growth, Finance ve Product “aktif müşteri”yi farklı tanımlıyor."},"review":{"happened":"Aynı isim üç farklı tanım taşıyordu.","discovered":"Metrik yönetişimi tanım, owner, kaynak, zaman penceresi ve değişiklik süreci gerektirir.","habit":"Metric contract oluştur ve tek owner ata.","watch":"Tek dashboard tek tanım demek değildir."},"steps":[{"type":"dialog","who":"maya","cta":"Devam","lines":["Üç ekip de doğru olduğunu söylüyor.","Sorun SQL değil yönetişim."]},{"type":"choice","label":"Çözüm","prompt":"Ne kurarsın?","goal":"Ortak metric contract.","options":[{"label":"En çok kullanılan dashboardu resmi ilan ederim","fb":"Tanım sorunu çözülmez."},{"label":"Tanım + owner + kaynak + pencere + versiyon/değişiklik onayı","correct":true,"fb":"Doğru."}]},{"type":"choice","label":"Transfer","prompt":"Metrik tanımı değişecek.","goal":"Change management.","options":[{"label":"Sessizce query’yi güncellerim","fb":"Tarihsel karşılaştırma kırılır."},{"label":"Eski/yeni tanımı versiyonlar, etki analizi ve geçiş tarihi yayınlarım","correct":true,"fb":"Doğru."}],"transfer":true}]},
{"id":"case051","num":"051","chapter":7,"title":"Yap mı Satın Al mı?","difficulty":5,"xp":280,"after":"case050","short":"Fraud platformunu içeride mi kurmalı, dışarıdan mı almalısınız?","tags":["leadership","strategy"],"nodes":["leadership","strategy"],"rewards":{"businessThinking":8,"statistics":6},"concept":{"name":"Build vs buy","en":"Build vs buy","text":"Build/buy kararı maliyet, hız, veri hassasiyeti, vendor lock-in ve stratejik avantajı birlikte tartar.","points":[]},"mentor":"TCO + time-to-value + risk + differentiation matrisi kullan.","portfolio":{"title":"Yap mı Satın Al mı?","text":"Fraud platformunu içeride mi kurmalı, dışarıdan mı almalısınız?"},"review":{"happened":"Teknik yetenek kadar toplam sahip olma maliyeti ve stratejik farklılaşma önemliydi.","discovered":"Build/buy kararı maliyet, hız, veri hassasiyeti, vendor lock-in ve stratejik avantajı birlikte tartar.","habit":"TCO + time-to-value + risk + differentiation matrisi kullan.","watch":"“Biz yapabiliriz” tek başına build gerekçesi değildir."},"steps":[{"type":"dialog","who":"alex","cta":"Devam","lines":["Vendor 6 ay kazandırıyor ama veriyi kendi bulutunda tutuyor.","Ekip içeride de yapabilir."]},{"type":"choice","label":"Karar","prompt":"İlk değerlendirme çerçeven?","goal":"Build-buy trade-off.","options":[{"label":"Sadece lisans fiyatı","fb":"Gizli maliyet/riskler var."},{"label":"TCO, hız, KVKK/güvenlik, lock-in, özelleştirme ve stratejik farklılaşma","correct":true,"fb":"Doğru."}]},{"type":"choice","label":"Transfer","prompt":"Çözüm şirketin ana rekabet avantajıysa?","goal":"Stratejik farklılaşmayı taşımak.","options":[{"label":"Her durumda vendor","fb":"Bağlama duyarsız."},{"label":"İçeride yetkinlik kurmanın değeri artar","correct":true,"fb":"Doğru."}],"transfer":true}]},
{"id":"case052","num":"052","chapter":7,"title":"İmkânsız Teslim Tarihi","difficulty":5,"xp":280,"after":"case051","short":"CEO 2 haftada 3 aylık proje istiyor. Lider olarak kapsamı yönet.","tags":["leadership","business"],"nodes":["leadership","business"],"rewards":{"businessThinking":8,"statistics":6},"concept":{"name":"Kapsam ve paydaş yönetimi","en":"Kapsam ve paydaş yönetimi","text":"Liderlik “hayır” demek değil; seçenek, risk ve minimum değerli kapsam sunmaktır.","points":[]},"mentor":"Süre-kapsam-kalite trade-off’unu görünür yap.","portfolio":{"title":"İmkânsız Teslim Tarihi","text":"CEO 2 haftada 3 aylık proje istiyor. Lider olarak kapsamı yönet."},"review":{"happened":"Takvim sabitken kapsamın pazarlık edilmesi gerekiyordu.","discovered":"Liderlik “hayır” demek değil; seçenek, risk ve minimum değerli kapsam sunmaktır.","habit":"Süre-kapsam-kalite trade-off’unu görünür yap.","watch":"Ekibi sessizce fazla mesaiye itme."},"steps":[{"type":"dialog","who":"ceo","cta":"Devam","lines":["İki hafta sonra yatırımcı demosu var. Tam sistemi istiyorum.","Yetişir, değil mi?"]},{"type":"choice","label":"Yanıt","prompt":"Ne dersin?","goal":"Gerçekçi commitment.","options":[{"label":"Tabii, ekip halleder","fb":"Gizli risk ve tükenme."},{"label":"İki haftada güvenli demo/pilot kapsamını, 3 ayda production kapsamını ve riskleri net sunarım","correct":true,"fb":"Net ve çözüm odaklı."}]},{"type":"choice","label":"Transfer","prompt":"CEO “yine de full scope” diyor.","goal":"Escalation ve risk sahipliği.","options":[{"label":"Testleri atlarım","fb":"Kalıcı borç."},{"label":"Riskleri yazılı hale getirip kalite/güvenlikten taviz vermeden sponsor kararı isterim","correct":true,"fb":"Doğru."}],"transfer":true}]},
{"id":"case053","num":"053","chapter":7,"title":"Ekip Hangi Projeye?","difficulty":5,"xp":280,"after":"case052","short":"Beş proje, iki ekip. Portföyü etki ve kapasiteyle önceliklendir.","tags":["leadership","strategy"],"nodes":["leadership","strategy"],"rewards":{"businessThinking":8,"statistics":6},"concept":{"name":"Portföy önceliklendirme","en":"Portföy önceliklendirme","text":"Portföy yönetimi etki, güven, efor, risk ve bağımlılıkları birlikte değerlendirir.","points":[]},"mentor":"Projeleri ortak kriterlerle puanla; kapasiteyi açıkça sınırla.","portfolio":{"title":"Ekip Hangi Projeye?","text":"Beş proje, iki ekip. Portföyü etki ve kapasiteyle önceliklendir."},"review":{"happened":"En parlak proje en yüksek net değer değildi.","discovered":"Portföy yönetimi etki, güven, efor, risk ve bağımlılıkları birlikte değerlendirir.","habit":"Projeleri ortak kriterlerle puanla; kapasiteyi açıkça sınırla.","watch":"HIPPO isteğini otomatik öncelik yapma."},"steps":[{"type":"dialog","who":"maya","cta":"Devam","lines":["İki squad var. Beş sponsor da “kritik” diyor.","Sen artık tek projeyi değil portföyü yönetiyorsun."]},{"type":"choice","label":"Seçim","prompt":"A: 9 etki/9 efor, B: 7/2, C: 8/3 ve veri hazır. İlk dalga?","goal":"Değer/efor ve hazırlık.","options":[{"label":"A ve CEO’nun favorisi","fb":"Kapasiteyi kilitler."},{"label":"B ve C; hızlı değer ve yüksek hazır etki","correct":true,"fb":"Dengeli portföy."}]},{"type":"choice","label":"Transfer","prompt":"Düşük etkili proje regülasyon zorunluluğu taşıyor.","goal":"Zorunlu işleri portföye katmak.","options":[{"label":"Etki düşük diye reddederim","fb":"Risk maliyetini yok sayar."},{"label":"Regülasyon riskini ayrı zorunlu kategori olarak kapasiteye dahil ederim","correct":true,"fb":"Doğru."}],"transfer":true}]},
{"id":"case054","num":"054","chapter":7,"title":"Lider Değerlendirmesi","difficulty":5,"xp":400,"after":"case053","short":"Teknik karar, ekip gelişimi ve portföyü aynı masada savun.","tags":["leadership","governance","strategy"],"nodes":["leadership","governance","strategy"],"rewards":{"businessThinking":8,"statistics":6},"concept":{"name":"Liderlik sentezi","en":"Liderlik sentezi","text":"Lead DS başarısı kendi modelinden çok ekibin tekrarlanabilir karar kalitesidir.","points":[]},"mentor":"Standartlar + mentorluk + portföy + ölçüm sistemi kur.","portfolio":{"title":"Lider Değerlendirmesi","text":"Teknik karar, ekip gelişimi ve portföyü aynı masada savun."},"review":{"happened":"Kurul yalnız sonuç değil karar sistemini sorguladı.","discovered":"Lead DS başarısı kendi modelinden çok ekibin tekrarlanabilir karar kalitesidir.","habit":"Standartlar + mentorluk + portföy + ölçüm sistemi kur.","watch":"Her kritik kararı kendinde toplama."},"steps":[{"type":"dialog","who":"ceo","cta":"Devam","lines":["Altı ayda neyi değiştirdin?","Model sayısını değil organizasyonun karar kalitesini anlat."]},{"type":"choice","label":"Final","prompt":"En güçlü cevap?","goal":"Lead seviyesinde sentez.","options":[{"label":"Ben en zor modelleri kendim yaptım","fb":"Bireysel katkı liderlik değildir."},{"label":"Ortak metric/model review standartları, mentorluk, risk tabanlı portföy ve sahiplik sistemi kurduk","correct":true,"fb":"Liderlik sistem kurar."}]},{"type":"choice","label":"Transfer","prompt":"Sen iki hafta yokken ekip karar verebiliyor mu?","goal":"Delegasyon ve sistem olgunluğu.","options":[{"label":"Hayırsa vazgeçilmezim","fb":"Bu ölçeklenemez."},{"label":"Evetse liderlik sistemi çalışıyor; karar hakları ve guardrail’ler açık olmalı","correct":true,"fb":"Doğru."}],"transfer":true}],"promotion":true}
];
CH7_CASES.forEach(c=>{c.kind="case";c.concept.points=[c.review.habit];CASES.push(c);CASE_BY_ID[c.id]=c;});

(()=>{const src={"le.review":["case049"],"le.feedback":["case049"],"le.prioritize":["case053","case054"],"gov.metric":["case050","case054"],"gov.model":["case049","case054"]};Object.entries(src).forEach(([cid,s])=>{const n=SKILL_TREE.find(n=>n.concepts.some(c=>c.id===cid));if(!n)return;const c=n.concepts.find(c=>c.id===cid);s.forEach(x=>{if(!c.src.includes(x))c.src.push(x)});CONCEPT_BY_ID[cid]={...c,node:n.id};});})();

Object.assign(MORNINGS,{
49:{scene:"standup",time:"08:39",title:"Liderlik masası",text:"Nexora’da yeni bir gün.",steps:[{type:"dialog",who:"maya",cta:"Güne başla",lines:["Bugün cevabı sen vermek yerine ekibin karar kalitesini yükselteceksin."]}]},
50:{scene:"standup",time:"08:40",title:"Liderlik masası",text:"Nexora’da yeni bir gün.",steps:[{type:"dialog",who:"maya",cta:"Güne başla",lines:["Bugün cevabı sen vermek yerine ekibin karar kalitesini yükselteceksin."]}]},
51:{scene:"standup",time:"08:41",title:"Liderlik masası",text:"Nexora’da yeni bir gün.",steps:[{type:"dialog",who:"maya",cta:"Güne başla",lines:["Bugün cevabı sen vermek yerine ekibin karar kalitesini yükselteceksin."]}]},
52:{scene:"standup",time:"08:42",title:"Liderlik masası",text:"Nexora’da yeni bir gün.",steps:[{type:"dialog",who:"maya",cta:"Güne başla",lines:["Bugün cevabı sen vermek yerine ekibin karar kalitesini yükselteceksin."]}]},
53:{scene:"standup",time:"08:43",title:"Liderlik masası",text:"Nexora’da yeni bir gün.",steps:[{type:"dialog",who:"maya",cta:"Güne başla",lines:["Bugün cevabı sen vermek yerine ekibin karar kalitesini yükselteceksin."]}]},
54:{scene:"standup",time:"08:44",title:"Liderlik masası",text:"Nexora’da yeni bir gün.",steps:[{type:"dialog",who:"maya",cta:"Güne başla",lines:["Bugün cevabı sen vermek yerine ekibin karar kalitesini yükselteceksin."]}]},
});
Object.entries(MORNINGS).forEach(([d,m])=>{if(+d>=49&&+d<=54)MORNING_DEFS[`morning${d}`]={id:`morning${d}`,kind:"morning",day:+d,...m};});
Object.assign(AFTER_CASE,{case049:"Gün kapanırken ofiste kısa bir değerlendirme yapılıyor. Yarın yeni bir karar var.",case050:"Gün kapanırken ofiste kısa bir değerlendirme yapılıyor. Yarın yeni bir karar var.",case051:"Gün kapanırken ofiste kısa bir değerlendirme yapılıyor. Yarın yeni bir karar var.",case052:"Gün kapanırken ofiste kısa bir değerlendirme yapılıyor. Yarın yeni bir karar var.",case053:"Gün kapanırken ofiste kısa bir değerlendirme yapılıyor. Yarın yeni bir karar var.",case054:"Gün kapanırken ofiste kısa bir değerlendirme yapılıyor. Yarın yeni bir karar var."});
