/* DATA TYCOON — Chapter 8 */
CH_START[8] = 55;
PROMOTIONS[8] = { title: "Veri Direktörü", req: {strategy:3,governance:2,leadership:3,"strategy@2":1} };
CH_PROMO_CASE[8] = "case059";
const CH8_CASES = [
{"id":"case055","num":"055","chapter":8,"title":"2 Milyon Avroluk YZ Bahsi","difficulty":5,"xp":280,"after":"case054","short":"Bütçe iki projeye yetiyor. Teknoloji değil portföy seç.","tags":["strategy","governance"],"nodes":["strategy","governance"],"rewards":{"businessThinking":8,"statistics":6},"concept":{"name":"AI yatırım portföyü","en":"AI yatırım portföyü","text":"Strateji etki, fizibilite, risk, hazırlık ve ölçüm planını birlikte tartar.","points":[]},"mentor":"Her yatırım için başarı metriği ve çıkış kriteri koy.","portfolio":{"title":"2 Milyon Avroluk YZ Bahsi","text":"Bütçe iki projeye yetiyor. Teknoloji değil portföy seç."},"review":{"happened":"Yüksek getiri tahmini en yüksek belirsizliği de taşıyordu.","discovered":"Strateji etki, fizibilite, risk, hazırlık ve ölçüm planını birlikte tartar.","habit":"Her yatırım için başarı metriği ve çıkış kriteri koy.","watch":"“AI yapmalıyız” strateji değildir."},"steps":[{"type":"dialog","who":"ceo","cta":"Devam","lines":["2 milyon avro. Üç teklif. İkisini seç.","Kurul senden teknoloji listesi değil yatırım tezi istiyor."]},{"type":"choice","label":"Portföy","prompt":"Forecast platformu: düşük risk/2.1x. Recommendation: orta risk/3x. GenAI: yüksek belirsizlik/0.8–4x. İlk yaklaşım?","goal":"Portföy dengesi.","options":[{"label":"En yüksek üst sınırı olan iki proje","fb":"Belirsizliği yok sayar."},{"label":"Hazır ve ölçülebilir bir çekirdek yatırım + kontrollü yüksek potansiyelli bahis","correct":true,"fb":"Dengeli strateji."}]},{"type":"choice","label":"Transfer","prompt":"Bir projenin ROI’si ölçülemiyor.","goal":"Ölçüm planı.","options":[{"label":"Önce başlatır sonra bakarım","fb":"Sunk cost riski."},{"label":"Yatırım öncesi baseline, başarı metriği ve stop kriteri tanımlarım","correct":true,"fb":"Doğru."}],"transfer":true}]},
{"id":"case056","num":"056","chapter":8,"title":"YZ Yönetişim Krizi","difficulty":5,"xp":280,"after":"case055","short":"Bir ekip müşteri verisiyle GenAI aracını onaysız kullanmış.","tags":["governance","responsible","strategy"],"nodes":["governance","responsible","strategy"],"rewards":{"businessThinking":8,"statistics":6},"concept":{"name":"AI governance","en":"AI governance","text":"YZ yönetişimi kullanım sınıfı, veri sınırı, değerlendirme, insan gözetimi ve onay yolunu risk bazlı tanımlar.","points":[]},"mentor":"Risk arttıkça kanıt ve onay seviyesi artsın.","portfolio":{"title":"YZ Yönetişim Krizi","text":"Bir ekip müşteri verisiyle GenAI aracını onaysız kullanmış."},"review":{"happened":"Hız uğruna veri ve model risk süreci atlanmıştı.","discovered":"YZ yönetişimi kullanım sınıfı, veri sınırı, değerlendirme, insan gözetimi ve onay yolunu risk bazlı tanımlar.","habit":"Risk arttıkça kanıt ve onay seviyesi artsın.","watch":"Yönetişimi yalnız belge üretimine dönüştürme."},"steps":[{"type":"dialog","who":"zeynep","cta":"Devam","lines":["Pilot ekip müşteri notlarını public LLM’e yapıştırmış.","Sonuçlar iyi ama süreç yok."]},{"type":"choice","label":"İlk karar","prompt":"Ne yaparsın?","goal":"Incident + governance.","options":[{"label":"Sonuç iyi, pilot devam","fb":"Gizlilik ve yönetişim riski."},{"label":"Veri akışını durdurur, etkiyi değerlendirir, güvenli ortam ve risk bazlı onay süreci kurarım","correct":true,"fb":"Doğru."}]},{"type":"choice","label":"Transfer","prompt":"Düşük riskli iç metin özetleme ile kredi kararı aynı süreç mi?","goal":"Risk bazlı governance.","options":[{"label":"Evet, her AI aynı","fb":"Orantısız süreç."},{"label":"Hayır; kullanım etkisine göre farklı güvence/onay seviyesi gerekir","correct":true,"fb":"Doğru."}],"transfer":true}]},
{"id":"case057","num":"057","chapter":8,"title":"Veri Organizasyonunu Kur","difficulty":5,"xp":280,"after":"case056","short":"Merkezi mi federatif mi? 60 kişilik veri organizasyonunu tasarla.","tags":["strategy","leadership","governance"],"nodes":["strategy","leadership","governance"],"rewards":{"businessThinking":8,"statistics":6},"concept":{"name":"Operating model","en":"Operating model","text":"Organizasyon tasarımı karar hakları, platform yetkinliği, domain sahipliği ve ortak standartları dengelemelidir.","points":[]},"mentor":"Merkezi platform/standart + domain’e yakın ekipler + net ownership.","portfolio":{"title":"Veri Organizasyonunu Kur","text":"Merkezi mi federatif mi? 60 kişilik veri organizasyonunu tasarla."},"review":{"happened":"Tek merkez iş bağlamından, tam dağıtık yapı standartlardan kopuyordu.","discovered":"Organizasyon tasarımı karar hakları, platform yetkinliği, domain sahipliği ve ortak standartları dengelemelidir.","habit":"Merkezi platform/standart + domain’e yakın ekipler + net ownership.","watch":"Org chartı strateji sanma."},"steps":[{"type":"dialog","who":"maya","cta":"Devam","lines":["Artık 60 kişiyiz. Her ekip farklı stack ve KPI kullanıyor.","Merkezileştirelim mi?"]},{"type":"choice","label":"Model","prompt":"En sürdürülebilir yaklaşım?","goal":"Operating model tasarımı.","options":[{"label":"Herkesi tek merkezi kuyruğa alırım","fb":"İş bağlamı ve hız kaybolabilir."},{"label":"Ortak platform/standartları merkezde, domain analitiğini iş birimlerine yakın; karar haklarını netleştiririm","correct":true,"fb":"Dengeli federatif model."}]},{"type":"choice","label":"Transfer","prompt":"Domain ekipleri standartları atlıyor.","goal":"Governance enforcement.","options":[{"label":"Daha fazla PDF yayınlarım","fb":"Davranış değişmeyebilir."},{"label":"Golden path, otomasyon ve istisna süreci kurarım","correct":true,"fb":"Yönetişimi kullanılabilir hale getirir."}],"transfer":true}]},
{"id":"case058","num":"058","chapter":8,"title":"YZ Bize Para Kazandırıyor mu?","difficulty":5,"xp":280,"after":"case057","short":"CEO tüm AI portföyünün gerçek ekonomik etkisini soruyor.","tags":["strategy","business","governance"],"nodes":["strategy","business","governance"],"rewards":{"businessThinking":8,"statistics":6},"concept":{"name":"AI ROI","en":"AI ROI","text":"AI ROI baseline, incremental etki, toplam maliyet, risk ve benimsenmeyi birlikte ölçer.","points":[]},"mentor":"Teknik KPI → kullanım → iş sonucu → finansal etki zinciri kur.","portfolio":{"title":"YZ Bize Para Kazandırıyor mu?","text":"CEO tüm AI portföyünün gerçek ekonomik etkisini soruyor."},"review":{"happened":"Model metriği ile finansal etki karıştırılmıştı.","discovered":"AI ROI baseline, incremental etki, toplam maliyet, risk ve benimsenmeyi birlikte ölçer.","habit":"Teknik KPI → kullanım → iş sonucu → finansal etki zinciri kur.","watch":"Tahmini faydayı gerçekleşmiş fayda gibi raporlama."},"steps":[{"type":"dialog","who":"ceo","cta":"Devam","lines":["Sunumlarda 14 model, 7 chatbot, milyonlarca tahmin var.","Peki para kazandık mı?"]},{"type":"choice","label":"Ölçüm","prompt":"En doğru çerçeve?","goal":"AI değer zinciri.","options":[{"label":"Toplam tahmin sayısı","fb":"Aktivite değer değildir."},{"label":"Baseline’a göre incremental gelir/maliyet etkisi eksi toplam sahip olma maliyeti; adoption ve riskle birlikte","correct":true,"fb":"Doğru."}]},{"type":"choice","label":"Transfer","prompt":"Bir asistan saat kazandırıyor ama kimse kullanmıyor.","goal":"Adoption etkisi.","options":[{"label":"Demo başarılıysa ROI vardır","fb":"Hayır."},{"label":"Potansiyel fayda gerçekleşmiş ROI değildir; kullanım/adoption çarpanı gerekir","correct":true,"fb":"Doğru."}],"transfer":true}]},
{"id":"case059","num":"059","chapter":8,"title":"Son Yönetim Kurulu","difficulty":5,"xp":500,"after":"case058","short":"12 yıllık yolculuğun finali: Nexora’nın üç yıllık Data & AI stratejisini savun.","tags":["strategy","governance","leadership","responsible"],"nodes":["strategy","governance","leadership","responsible"],"rewards":{"businessThinking":8,"statistics":6},"concept":{"name":"Data & AI stratejisi","en":"Data & AI stratejisi","text":"Olgun strateji portföy, veri temeli, yetenek, yönetişim, işletim modeli ve ölçülebilir iş etkisini tek sistemde birleştirir.","points":[]},"mentor":"Stratejiyi 3–5 öncelik, sahiplik, yatırım, KPI ve stop kriteriyle somutlaştır.","portfolio":{"title":"Son Yönetim Kurulu","text":"12 yıllık yolculuğun finali: Nexora’nın üç yıllık Data & AI stratejisini savun."},"review":{"happened":"Kurul tek proje değil yön, ölçüm ve risk çerçevesi istedi.","discovered":"Olgun strateji portföy, veri temeli, yetenek, yönetişim, işletim modeli ve ölçülebilir iş etkisini tek sistemde birleştirir.","habit":"Stratejiyi 3–5 öncelik, sahiplik, yatırım, KPI ve stop kriteriyle somutlaştır.","watch":"Vizyonu proje listesine indirgeme."},"steps":[{"type":"dialog","who":"ceo","cta":"Devam","lines":["İlk gününde Maya sana İzmir’e bak demişti.","Bugün soru şu: Nexora önümüzdeki üç yıl nereye bakmalı?"]},{"type":"choice","label":"Strateji","prompt":"Kurula hangi çerçeveyi sunarsın?","goal":"Final sentezi.","options":[{"label":"Daha fazla model ve daha büyük LLM","fb":"Teknoloji listesi strateji değildir."},{"label":"1) veri temeli 2) ölçülebilir AI portföyü 3) güvenli platform/MLOps 4) sorumlu yönetişim 5) yetenek ve operating model; her biri KPI ve owner ile","correct":true,"fb":"Tam bir işletim stratejisi."}]},{"type":"choice","label":"Son karar","prompt":"Başarıyı nasıl yöneteceksin?","goal":"Stratejiyi ölçülebilir yapmak.","options":[{"label":"Yıllık sunumda proje sayısını artırırım","fb":"Aktivite odaklı."},{"label":"Çeyreklik portföy review: gerçekleşen değer, risk, adoption ve stop/scale kararları","correct":true,"fb":"Şirket düzeyinde öğrenme döngüsü."}]},{"type":"dialog","who":"maya","cta":"Kariyeri tamamla","lines":["Telefonuna bir mesaj düşüyor.","“İlk gün hangi bölgeye bakacağını söylüyordum. Bugün şirketin hangi yöne bakacağını sen söylüyorsun. Gurur duyuyorum.”"]}],"promotion":true}
];
CH8_CASES.forEach(c=>{c.kind="case";c.concept.points=[c.review.habit];CASES.push(c);CASE_BY_ID[c.id]=c;});

(()=>{const src={"str.portfolio":["case055","case059"],"str.roi":["case058","case059"],"str.org":["case057","case059"],"gov.metric":["case057"],"gov.model":["case056"]};Object.entries(src).forEach(([cid,s])=>{const n=SKILL_TREE.find(n=>n.concepts.some(c=>c.id===cid));if(!n)return;const c=n.concepts.find(c=>c.id===cid);s.forEach(x=>{if(!c.src.includes(x))c.src.push(x)});CONCEPT_BY_ID[cid]={...c,node:n.id};});})();

Object.assign(MORNINGS,{
55:{scene:"standup",time:"08:45",title:"Direktör gündemi",text:"Nexora’da yeni bir gün.",steps:[{type:"dialog",who:"maya",cta:"Güne başla",lines:["Bugün tek projeyi değil şirket yönünü belirleyeceksin."]}]},
56:{scene:"standup",time:"08:46",title:"Direktör gündemi",text:"Nexora’da yeni bir gün.",steps:[{type:"dialog",who:"maya",cta:"Güne başla",lines:["Bugün tek projeyi değil şirket yönünü belirleyeceksin."]}]},
57:{scene:"standup",time:"08:47",title:"Direktör gündemi",text:"Nexora’da yeni bir gün.",steps:[{type:"dialog",who:"maya",cta:"Güne başla",lines:["Bugün tek projeyi değil şirket yönünü belirleyeceksin."]}]},
58:{scene:"standup",time:"08:48",title:"Direktör gündemi",text:"Nexora’da yeni bir gün.",steps:[{type:"dialog",who:"maya",cta:"Güne başla",lines:["Bugün tek projeyi değil şirket yönünü belirleyeceksin."]}]},
59:{scene:"standup",time:"08:49",title:"Direktör gündemi",text:"Nexora’da yeni bir gün.",steps:[{type:"dialog",who:"maya",cta:"Güne başla",lines:["Bugün tek projeyi değil şirket yönünü belirleyeceksin."]}]},
});
Object.entries(MORNINGS).forEach(([d,m])=>{if(+d>=55&&+d<=59)MORNING_DEFS[`morning${d}`]={id:`morning${d}`,kind:"morning",day:+d,...m};});
Object.assign(AFTER_CASE,{case055:"Gün kapanırken ofiste kısa bir değerlendirme yapılıyor. Yarın yeni bir karar var.",case056:"Gün kapanırken ofiste kısa bir değerlendirme yapılıyor. Yarın yeni bir karar var.",case057:"Gün kapanırken ofiste kısa bir değerlendirme yapılıyor. Yarın yeni bir karar var.",case058:"Gün kapanırken ofiste kısa bir değerlendirme yapılıyor. Yarın yeni bir karar var.",case059:"Gün kapanırken ofiste kısa bir değerlendirme yapılıyor. Yarın yeni bir karar var."});
