/* DATA TYCOON v4.0 — Office immersion layer: recurring human moments across the career. */
(function(){
  const moments=[
    {id:'ev40_whiteboard',who:'maya',days:[8,14],notify:'Beyaz tahtanın önüne gelir misin?',title:'Beş dakikalık beyaz tahta',xp:18,rewards:{businessThinking:3},steps:[{type:'dialog',who:'maya',cta:'Tahtaya geç',lines:['Maya laptopunu kapatıp ayağa kalkıyor. “Bir dakika ekrandan uzaklaşalım.”','Tahtaya üç kelime yazıyor: Problem → Ölçüm → Karar. “Sorgudan önce hangisi eksik?”']},{type:'choice',who:'maya',prompt:'Bir stakeholder “dashboard yavaş” dedi. İlk sorun nedir?',goal:'Teknik talebi karar problemine çevirmek.',options:[{label:'Hangi sorguyu optimize edeceğimizi seçmek',fb:'Çözüm uzayına çok erken girdin.'},{label:'Yavaşlığın hangi kullanıcı kararını veya iş akışını etkilediğini netleştirmek',correct:true,fb:'Maya kalemi sana uzatıyor: “Önce karar. Sonra teknik.”'},{label:'Dashboard aracını değiştirmek',fb:'Kök problem bilinmeden araç değiştirmek pahalı bir tahmindir.'}]}]},
    {id:'ev40_lunch',who:'buse',days:[18,28],notify:'Öğle yemeğinde bir şey sorabilir miyim?',title:'Buse ile öğle arası',xp:16,rewards:{statistics:2,businessThinking:2},steps:[{type:'dialog',who:'buse',cta:'Dinle',lines:['Buse tepsisini masaya bırakıyor. “Bir şeyi ezberleyince biliyorum sanıyorum.”','“Sen artık bir analizi gerçekten anladığını nasıl test ediyorsun?”']},{type:'choice',who:'buse',prompt:'Buse’ye hangi yöntemi önerirsin?',goal:'Transfer yoluyla öğrenmeyi doğrulamak.',options:[{label:'Tanımı üç kez tekrar etmek',fb:'Hatırlamayı ölçer, transferi değil.'},{label:'Aynı kavramı farklı bir iş probleminde, ipucusuz uygulamaya çalışmak',correct:true,fb:'Buse not alıyor: “Yeni bağlamda kullanabiliyorsam gerçekten öğrenmişim.”'},{label:'Daha uzun not çıkarmak',fb:'Not yararlı olabilir ama uygulama kanıtı değildir.'}]}]},
    {id:'ev40_corridor',who:'maya',days:[33,40],notify:'Koridorda seni yakalıyor',title:'Asansör kapısında',xp:18,rewards:{businessThinking:3},steps:[{type:'dialog',who:'maya',cta:'Devam',lines:['Toplantıdan çıkarken Maya sana yetişiyor. “Model sunumunu gördüm.”','“Bir sonraki sunumda bana model adını en son söyle. Önce hangi kararı değiştirdiğini anlat.”']},{type:'choice',who:'maya',prompt:'Yöneticiye model sonucunu hangi sırayla anlatırsın?',goal:'Teknik çıktıyı karar diline çevirmek.',options:[{label:'Algoritma → hiperparametre → AUC → iş kararı',fb:'Karar sahibi için sıra ters.'},{label:'Karar → beklenen etki/risk → kanıt → gerekli olduğunda model detayı',correct:true,fb:'Maya: “Tam olarak bu.”'},{label:'Sadece model metriği; detay isteyen sorar',fb:'Metriğin neyi değiştirdiği belirsiz kalır.'}]}]},
    {id:'ev40_incidentcoffee',who:'deniz',days:[41,48],notify:'Kahve makinesinin yanında seni bekliyor',title:'Incident sonrası kahve',xp:18,rewards:{dataQuality:2,businessThinking:2},steps:[{type:'dialog',who:'deniz',cta:'Kahveni al',lines:['Deniz iki espresso koyuyor. “Dün geceki alarmdan sonra herkes retrain diyordu.”','“Bazen hiçbir şey yapmamak da aksiyon, değil mi?”']},{type:'choice',who:'deniz',prompt:'Ne zaman “hemen retrain etme” kararı doğrudur?',goal:'Alarm, kök neden ve müdahaleyi ayırmak.',options:[{label:'Alarmın veri pipeline kaynaklı olma ihtimali doğrulanmadan önce',correct:true,fb:'Deniz: “Evet. Bozuk veriye retrain yeni model değil, yeni incident üretir.”'},{label:'Model sahibi toplantıdaysa',fb:'Organizasyonel gecikme teknik karar kriteri değildir.'},{label:'AUC hâlâ 0,80 üzerindeyse her zaman',fb:'Tek metrik incident bağlamını açıklamaz.'}]}]},
    {id:'ev40_buse_review',who:'buse',days:[49,54],notify:'PR’ına bakabilir misin?',title:'Buse’nin PR’ı',xp:20,rewards:{businessThinking:3,statistics:2},steps:[{type:'dialog',who:'buse',cta:'PR’ı aç',lines:['Buse ekranını sana çeviriyor. “Testler geçiyor ama içime sinmedi.”','Kod doğru çalışıyor. Fakat feature tablosunda `latest_status` alanı var.']},{type:'choice',who:'buse',prompt:'Lead olarak ilk yorumun?',goal:'Cevabı vermek yerine düşünme standardını öğretmek.',options:[{label:'Alanı sil ve PR’ı merge et',fb:'Sorunu çözdün ama Buse’nin karar kasını geliştirmedin.'},{label:'“Bu alan prediction anında gerçekten mevcut muydu?” diye sorup zaman erişilebilirliğini birlikte doğrulamak',correct:true,fb:'Buse duruyor: “Haklısın… snapshot bugünden geliyor.”'},{label:'Model skoru yüksekse bırakmak',fb:'Leakage yüksek skorun nedeni olabilir.'}]}]},
    {id:'ev40_boardhall',who:'ceo',days:[55,59],notify:'Andrew toplantı öncesi iki dakika istiyor',title:'Kurul öncesi koridor',xp:20,rewards:{businessThinking:4},steps:[{type:'dialog',who:'ceo',cta:'Dinle',lines:['Andrew dosyalarını koltuğunun altına sıkıştırmış. “Sunumdan önce tek şey soracağım.”','“Bu AI yatırımı tutmazsa ne zaman vazgeçeceğiz?”']},{type:'choice',who:'ceo',prompt:'Direktör seviyesinde en güçlü cevap?',goal:'Yatırımı ölçülebilir stop/scale kriterleriyle yönetmek.',options:[{label:'Stratejik olduğu için en az iki yıl devam ederiz',fb:'Strateji sunk cost dokunulmazlığı değildir.'},{label:'Başlamadan baseline, başarı eşiği, risk limiti ve review tarihi koyar; kanıt oluşmazsa stop/pivot ederiz',correct:true,fb:'Andrew başını sallıyor: “Sunumda bunu söyle.”'},{label:'Vendor roadmap’ine göre karar veririz',fb:'Karar hakkını dışarı devrediyor.'}]}]}
  ];
  moments.forEach(e=>{e.kind='event';e.modal=true;EVENTS.push(e);EVENT_BY_ID[e.id]=e});
  window.DT_IMMERSION_V4={version:'4.0',moments:moments.length};
})();
